# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
# Specifies the version of the Dependabot configuration format being used.

updates:
  # Defines the list of dependencies or package ecosystems to monitor for updates.

  - package-ecosystem: "terraform"
    # Specifies that the package ecosystem is Terraform, so Dependabot will check for updates to Terraform modules and providers.

    directory: "/"
    # Indicates the directory to check for dependency files (like .tf files or lockfiles).
    # "/" means it will check in the root directory of the repository.

    schedule:
      interval: "weekly"
      # Sets the frequency of the update checks. Here, Dependabot will check for updates once a week.

